---
- name: Install nginx with vhosts
  hosts: webservers
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: false

  vars:
    sites:
      - "fizfak.com"
      - "mehmat.com"
      - "biofak.com"

  roles:
    - nginx_vhosts
